[twig]
templateDir = 'templates'
templateCacheDir = '../var/twig-cache'

[twig-asset]
assetCompiledPath = 'templates/assets/cache'
assetUrlBasePath = 'templates/assets/cache/'
assetRuntimeCachePath = '../var/twig-assets-cache'
assetRuntimeCacheName = 'twig-assets-cache'
assetRuntimeCacheLifetime = 0
assetMinify = 0
